# HTTP Server配置
[server]
	Address        = ":8199"
	ServerRoot     = "public"
	ServerAgent    = "gf-demos"
	LogPath        = "E:/Gowww/src/kong1/public/log/default"
	NameToUriType  = 2
	RouteOverWrite = true
	UploadPath     = "E:/Gowww/src/kong1/public/upload"

# 全局日志配置
[logger]
    Path   = "E:/Gowww/src/kong1/public/log/default"
    Level  = "all"
    Stdout = true

# 模板引擎配置
[viewer]
    Path        = "template"
    DefaultFile = "index.html"
    Delimiters  =  ["${", "}"]

# 数据库连接
[database]
    link  = "mysql:root:root@tcp(127.0.0.1:3306)/kongone"
    debug = true
    # 数据库日志对象配置
    [database.logger]
        Path   = "E:/Gowww/src/kong1/public/sql"
        Level  = "all"
        Stdout = true